apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: cb22482fd8bfbab96d67ca0326b7de86d71ccd94
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: cb22482fd8bfbab96d67ca0326b7de86d71ccd94
