apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 6a4a6468257941ad967c277d70fa9b1a3551f7c7
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 6a4a6468257941ad967c277d70fa9b1a3551f7c7
