apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 3539fd26ff6ec63cbd612fb0193476d6fb77c003
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 3539fd26ff6ec63cbd612fb0193476d6fb77c003
