apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: a6348004cd9e1c963a2bf96e197a0d9b1417813e
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: a6348004cd9e1c963a2bf96e197a0d9b1417813e
