apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
  - frontend
  - backend

images:
  - name: frontend-placeholder
    newName: docker.io/nailien/chess-frontend
    newTag: 0c9d1d6ac8c787b8fba083a4619b5566d441c869
  - name: backend-placeholder
    newName: docker.io/nailien/chess-backend
    newTag: 0c9d1d6ac8c787b8fba083a4619b5566d441c869
