apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: b4df24e2d61702a6fad0b1dfb827c08949dc959a
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: b4df24e2d61702a6fad0b1dfb827c08949dc959a
