apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: f47c9398458035dd8eab8cebdd2961c31ee4a4bb
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: f47c9398458035dd8eab8cebdd2961c31ee4a4bb
