apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: c8913945ac4e6d5a2498a4528ea7c3b4bd553e6e
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: c8913945ac4e6d5a2498a4528ea7c3b4bd553e6e
