apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 1e210ff3b8b85f2a15e9986e1cd4b707c5805da0
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 1e210ff3b8b85f2a15e9986e1cd4b707c5805da0
