apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 05ec14c27d35efb3360e06640eeab101db38cc87
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 05ec14c27d35efb3360e06640eeab101db38cc87
