apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend

  newTag: c920b777eeb61bb63bfbb30d1457cdde15f0da3d
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: c920b777eeb61bb63bfbb30d1457cdde15f0da3d

