apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 22454837f4df005468df70a0237368f450a3dad1
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 22454837f4df005468df70a0237368f450a3dad1
