apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 6801dfb5121a288cd6c55ffd1975e096ebb4d368
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 6801dfb5121a288cd6c55ffd1975e096ebb4d368
