apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: b38c5459eecc4ec2903a7fe2e4225ec25b01a284
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: b38c5459eecc4ec2903a7fe2e4225ec25b01a284
