apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 7b40fdb11e2b66c0ba8c98dc60b11ac6b0d1dbcc
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 7b40fdb11e2b66c0ba8c98dc60b11ac6b0d1dbcc
