apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: e56e2e76588ca52d174f0341af0bff90f6afc637
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: e56e2e76588ca52d174f0341af0bff90f6afc637
