apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 4bb34d5db7a35f354acecfc5e84fd2c3177a6580
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 4bb34d5db7a35f354acecfc5e84fd2c3177a6580
