apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 4874039bc518c9261e3f4852fd8b7c177ae593f7
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 4874039bc518c9261e3f4852fd8b7c177ae593f7
