apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 4f85e282c45cc369833174f71f5acdeef0dea698
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 4f85e282c45cc369833174f71f5acdeef0dea698
