apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: c168e430fc8b29195cf6e69ff63d1d80370c41b2
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: c168e430fc8b29195cf6e69ff63d1d80370c41b2
