apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 91ab08b4ecd9d912db1adfd12136605b614bf15b
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 91ab08b4ecd9d912db1adfd12136605b614bf15b
