apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: ea9927aa16242f265231cd5960fd754fa229a5c8
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: ea9927aa16242f265231cd5960fd754fa229a5c8
