apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 40e3fceeb6c2313ac99cf663ceae7fb22f405cd1
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 40e3fceeb6c2313ac99cf663ceae7fb22f405cd1
