apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 37a552a8ce787855a19ce1e903b5e714b09a468d
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 37a552a8ce787855a19ce1e903b5e714b09a468d
