apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 4533004384890f8d937020e3e8d7130f4eeb558f
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 4533004384890f8d937020e3e8d7130f4eeb558f
