apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend
  - backend

images:
  - name: frontend-placeholder
    newName: docker.io/<cevdet_username>/chess-frontend
    newTag: <tag>
  - name: backend-placeholder
    newName: docker.io/<cevdet_username>/chess-backend
    newTag: <tag>
