apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 27951cefb22e08aa63f4ef499c9f735b8996154c
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 27951cefb22e08aa63f4ef499c9f735b8996154c
