apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 6e5a2b47c060e5667cf16dbaf1bb18aba2054897
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 6e5a2b47c060e5667cf16dbaf1bb18aba2054897
