apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: c3abd843b16a88aeac790778426ba10c1e7b8412
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: c3abd843b16a88aeac790778426ba10c1e7b8412
