apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres


images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: f5983a03ad354f555149265f37a5a7b5bf024aff
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: f5983a03ad354f555149265f37a5a7b5bf024aff
