apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend

  newTag: 12014e737b72f963b10b2dff7b4db1e6b51a506c
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 12014e737b72f963b10b2dff7b4db1e6b51a506c

