apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 895220e67cfd59d0de03dea020f4ea83ccb6f27e
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 895220e67cfd59d0de03dea020f4ea83ccb6f27e
