apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 7e176369c30c545441438fba51dfeb48a8386a31
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 7e176369c30c545441438fba51dfeb48a8386a31
