apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 9e0082ea2860c4276bda24687842698fe03d1441
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 9e0082ea2860c4276bda24687842698fe03d1441
