apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 9a2b08b2c08682b1242ed949a0071dba89611f03
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 9a2b08b2c08682b1242ed949a0071dba89611f03
