apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 2e1369d90e483aafffbfc57f42477068ac8f94b3
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 2e1369d90e483aafffbfc57f42477068ac8f94b3
