apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- frontend
- backend

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 8444d7b706348a15c57f950eccda3349a66696ad
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 8444d7b706348a15c57f950eccda3349a66696ad
