apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: 5b4ec0bfa1c74a3070a4d88304bf57e7a2695517
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: 5b4ec0bfa1c74a3070a4d88304bf57e7a2695517
