apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces
- postgres-operator
- frontend
- backend
- postgres

images:
- name: backend-placeholder
  newName: docker.io/nailien/chess-backend
  newTag: d586ee71cd6cf2fdbfa5b827ec1db4637d07bcbd
- name: frontend-placeholder
  newName: docker.io/nailien/chess-frontend
  newTag: d586ee71cd6cf2fdbfa5b827ec1db4637d07bcbd
