apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
  - frontend
  - backend

images:
  - name: frontend-placeholder
    newName: docker.io/nailien/chess-frontend
    newTag: c426f7222afd039b31e37fc28f48e6abf8a5e4b1
  - name: backend-placeholder
    newName: docker.io/nailien/chess-backend
    newTag: c426f7222afd039b31e37fc28f48e6abf8a5e4b1
