
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chess-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chess-backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: chess-backend
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          image: backend-placeholder
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: user
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: dbname
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: host
          envFrom:
            - configMapRef:
                name: config-backend
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
