apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: chess-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chess-frontend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: chess-frontend
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false # TODO: change to true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          image: frontend-placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-frontend
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx
            - name: cache
              mountPath: /var/cache/nginx
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf  # Mount the specific file from ConfigMap
      volumes:
        - name: logs
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: cache
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
        - name: nginx-config
          configMap:
            name: config-nginx
            items:
              - key: default.conf
                path: default.conf
