apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: &host chess.dev.adamland.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chess-frontend
                port:
                  number: 80
  tls:
    - hosts: [*host]
      secretName: chess-frontend-tls
