apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chess-dev

resources:
- configmap.yaml
- configmap-nginx.yaml
- deployment.yaml
- ingress.yaml
- pod-disruption-budget.yaml
- service.yaml
