name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: server
        file: ./server/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: nailien/chess-backend:${{ github.sha }}
        cache-from: type=registry,ref=nailien/chess-backend:buildcache
        cache-to: type=registry,ref=nailien/chess-backend:buildcache,mode=max

  build-client:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3      
    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Load environment variables from .env file
      run: |
        export $(grep -v `^#` client/.env | xargs)
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: client
        file: ./client/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: nailien/chess-frontend:${{ github.sha }}
        cache-from: type=registry,ref=nailien/chess-frontend:buildcache
        cache-to: type=registry,ref=nailien/chess-frontend:buildcache,mode=max
        build-args: |
          REACT_APP_BACKEND_URL=http://chess-backend
          REACT_APP_BACKEND_PORT=8080

  deploy-to-dev:
    if: github.ref == 'refs/heads/main'
    needs:
    - build-server
    - build-client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.0.0

      - name: Deploy new tags
        run: |
          set -euxo pipefail
          cd deploy/dev
          kustomize edit set image 'frontend-placeholder=docker.io/nailien/chess-frontend:${{ github.sha }}'
          kustomize edit set image 'backend-placeholder=docker.io/nailien/chess-backend:${{ github.sha }}'
          
          git config --global user.email "ci-bot@example.com"
          git config --global user.name "ci-bot"
          git add kustomization.yaml
          git commit -m "bot: deploy image tags ${{ github.sha }}"
          git push
