name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd server
    - uses: actions/setup-go@v4.1.0
    - run: go test ./...          
    - name: Build
      run: docker build server --tag chess-server:${{ github.sha }}

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd _chess-client/chess-client
    - name: Build
      run: docker build _chess-client/chess-client --tag chess-client:${{ github.sha }}
